"""empty message

Revision ID: dfadbecbcc4b
Revises: 
Create Date: 2024-03-17 20:15:12.769513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfadbecbcc4b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.drop_column('meta')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('meta', sa.VARCHAR(length=80), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
